[default]
static_dir = "../fridge-door-web/build"

[default.databases.fridge-door]
url = "db/fridge-door.db"

[release.databases.fridge-door]
url = "sqlite:///var/fridge-door/fridge-door.db"

[release]
address = "0.0.0.0"
port = 80
static_dir = "/var/fridge-door/static"
